language: python
jobs:
  include:
  - python:
    - "3.6"      # current default Python on Travis CI
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.9-dev"  # 3.8 development branch
    - "nightly"  # nightly build
  - name: "Python 3.7.4 on macOS"
    os: osx
    osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
    language: shell       # 'language: python' is an error on Travis CI macOS
  - name: "Python 3.8.0 on Windows"
    os: windows           # Windows 10.0.17134 N/A Build 17134
    language: shell       # 'language: python' is an error on Travis CI Windows
    before_install:
      - choco install python --version 3.8.0
      - python -m pip install --upgrade pip
    env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
# command to install dependencies
install:
  - pip3 install -U pip
  - pip install -U -r requirements.txt
  - pip install -U coverage pytest pytest-asyncio
# command to run tests
script:
  - python3 -m coverage run -m pytest || python -m coverage run -m pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
